"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = __importDefault(require("react"));
var spotifybg_jpg_1 = __importDefault(require("../assets/spotifybg.jpg"));
var monstercartoon_png_1 = __importDefault(require("../assets/monstercartoon.png"));
var Spotifylogo_png_1 = __importDefault(require("../assets/Spotifylogo.png"));
var YourComponent = function () { return (react_1.default.createElement("div", { style: {
        width: '100vw',
        height: '100vh',
        position: 'relative',
        overflow: 'hidden',
    } },
    react_1.default.createElement("div", { style: {
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            backgroundImage: 'linear-gradient(rgba(174, 248, 174, 1), rgba(255, 255, 255, 1))',
            opacity: 1,
            zIndex: 0,
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            backgroundRepeat: 'no-repeat',
        } }),
    react_1.default.createElement("div", { style: {
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            backgroundImage: "url(".concat(spotifybg_jpg_1.default, ")"),
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            backgroundRepeat: 'no-repeat',
            opacity: 0.2,
            zIndex: 1,
        } }),
    react_1.default.createElement("div", { style: {
            width: 666,
            height: 693,
            right: '17%',
            top: '45%',
            transform: 'translateY(-50%)',
            position: 'absolute',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 2,
            backgroundColor: 'rgba(30, 215, 96, 0.5)',
            boxShadow: '15px 18px 11.1px 5px rgba(0, 0, 0, 0.80)',
            borderRadius: '50%',
            border: '3px solid black',
            padding: 20,
            boxSizing: 'border-box',
        } },
        react_1.default.createElement("div", { style: {
                position: 'relative',
                width: 505,
                height: 502,
            } },
            react_1.default.createElement("img", { style: {
                    width: 254,
                    height: 315,
                    position: 'absolute',
                    left: 0,
                    top: 170,
                    filter: 'brightness(20%)',
                }, src: monstercartoon_png_1.default, alt: "Monster Cartoon" }),
            react_1.default.createElement("img", { style: {
                    width: 253,
                    height: 315,
                    position: 'absolute',
                    left: 252,
                    top: 170,
                    filter: 'brightness(20%)',
                }, src: monstercartoon_png_1.default, alt: "Monster Cartoon" }),
            react_1.default.createElement("img", { style: {
                    width: 406,
                    height: 502,
                    position: 'absolute',
                    left: 50,
                    top: 0,
                }, src: monstercartoon_png_1.default, alt: "Monster Cartoon" }))),
    react_1.default.createElement("div", { style: {
            left: 86,
            top: 38,
            position: 'absolute',
            justifyContent: 'center',
            alignItems: 'flex-start',
            gap: 3,
            display: 'inline-flex',
            zIndex: 3,
        } },
        react_1.default.createElement("div", { style: {
                color: 'black',
                fontSize: 30,
                fontFamily: 'Montserrat',
                fontWeight: 700,
                wordWrap: 'break-word',
            } }, "YourMusicCharacter"),
        react_1.default.createElement("img", { style: {
                width: 38,
                height: 40,
            }, src: Spotifylogo_png_1.default, alt: "Spotify Logo" })),
    react_1.default.createElement("div", { style: {
            width: 618,
            height: 84,
            left: 262,
            top: 727,
            position: 'absolute',
            zIndex: 3,
        } },
        react_1.default.createElement("div", { style: {
                width: 618,
                height: 84,
                left: 250,
                top: 100,
                position: 'absolute',
                background: 'black',
                boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)',
                borderRadius: 15,
                border: '2px solid black',
            } }),
        react_1.default.createElement("div", { style: {
                width: 517,
                height: 48,
                left: 300,
                top: 112,
                position: 'absolute',
                textAlign: 'center',
                zIndex: 4,
            } },
            react_1.default.createElement("span", { style: {
                    color: 'white',
                    fontSize: 35,
                    fontFamily: 'Montserrat',
                    fontWeight: 700,
                    wordWrap: 'break-word',
                } }, " Link Your "),
            react_1.default.createElement("span", { style: {
                    color: '#1ED760',
                    fontSize: 35,
                    fontFamily: 'Montserrat',
                    fontWeight: 700,
                    wordWrap: 'break-word',
                } }, "Spotify"),
            react_1.default.createElement("span", { style: {
                    color: 'white',
                    fontSize: 35,
                    fontFamily: 'Montserrat',
                    fontWeight: 700,
                    wordWrap: 'break-word',
                } }, " Account!"),
            react_1.default.createElement("span", { style: {
                    color: 'white',
                    fontSize: 40,
                    fontFamily: 'Montserrat',
                    fontWeight: 700,
                    wordWrap: 'break-word',
                } }, " "))),
    react_1.default.createElement("div", { style: {
            left: 424,
            top: 282,
            position: 'absolute',
            justifyContent: 'center',
            alignItems: 'center',
            display: 'inline-flex',
            zIndex: 3,
        } },
        react_1.default.createElement("div", { style: {
                color: 'black',
                fontSize: 140,
                fontFamily: 'Montserrat',
                fontWeight: 800,
                wordWrap: 'break-word',
            } }, "Welcome!")),
    react_1.default.createElement("div", { style: {
            left: 512,
            top: 465,
            position: 'absolute',
            justifyContent: 'center',
            alignItems: 'center',
            display: 'inline-flex',
            zIndex: 3,
        } },
        react_1.default.createElement("div", { style: {
                color: 'black',
                fontSize: 40,
                fontFamily: 'Montserrat',
                fontWeight: 700,
                wordWrap: 'break-word',
            } }, "To A Spotify Personality Test")),
    react_1.default.createElement("div", { style: {
            width: 725,
            height: 111,
            left: 452,
            top: 555,
            position: 'absolute',
            justifyContent: 'center',
            alignItems: 'center',
            display: 'inline-flex',
            zIndex: 3,
        } },
        react_1.default.createElement("div", { style: {
                width: 725,
                color: 'black',
                fontSize: 30,
                fontFamily: 'Montserrat',
                fontWeight: 500,
                wordWrap: 'break-word',
            } },
            "Sign in to Your Spotify Account Then Get ",
            react_1.default.createElement("br", null),
            "Personality-Based Cartoon Characters From ",
            react_1.default.createElement("br", null),
            "Your Top 5 Most Listened to Spotify Songs!")),
    react_1.default.createElement("div", { style: {
            position: 'absolute',
            bottom: 0,
            width: '100%',
            height: '80px',
            background: 'rgba(0, 0, 0, 0.20)',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            color: 'black',
            fontFamily: 'Montserrat',
            fontWeight: 700,
            fontSize: 24,
        } }, "A Tech Cadet Project"))); };
exports.default = YourComponent;
